apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    version: 1
    uid: prometheus
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger
          urlDisplayLabel: View in Jaeger
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      interval: 30s
      timeInterval: 30s
      customQueryParameters: ""

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    editable: true
    basicAuth: false
    withCredentials: false
    version: 1
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
          - key: span.name
            value: operation
        queries:
          - name: Sample query
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service.name
          - trace.id
        mappedTags:
          - datasourceUid: loki
        mapTagNamesEnabled: false
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    editable: true
    basicAuth: false
    withCredentials: false
    version: 1
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '"trace_id":"([^"]*)"'
          url: '$${__value.raw}'
          datasourceUid: jaeger